spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/artwork_statistics?useSSL=false&serverTimezone=UTC}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

logging:
  level:
    root: INFO
    com.example.artwork_statistics: INFO 