spring:
  datasource:
    url: jdbc:mysql://${AZURE_MYSQL_HOST}:${AZURE_MYSQL_PORT:3306}/${AZURE_MYSQL_DATABASE}?useSSL=true&requireSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${AZURE_MYSQL_USERNAME}
    password: ${AZURE_MYSQL_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false  # 프로덕션에서는 SQL 로그 비활성화
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

external-services:
  exhibition-artwork:
    base-url: ${EXHIBITION_SERVICE_URL:http://localhost:8081}
    timeout: 5000

logging:
  level:
    com.example.artwork_statistics: INFO
    org.springframework.web.client: WARN

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json 